### ISSUE TITLE
No parser can handle this stream

### ISSUE THREAD

**Issue by shairyar** [alexdebril/FeedIoBundle#21]
What is the main reason behind getting this error? If you look at [this](http://www.salesprorecruitment.co.uk/listing-feeds/?feedId=1) feed when i try to fetch it it gives an error so I am trying to find out the reason.

Can you please in what case this error is thrown and if there can be any work around?

**Comment by alexdebril** [comment]
Hi,

This is because the XML stream is neither a RSS or ATOM feed, so that's not a schema feed-io was built for. Meanwhile, it's possible to make feed-io support it by adding a new standard to it : 

```php
$feedIo = $this->container->get('feedio');

$jobStandard = new \Shairyar\Job\Standard();

$feedIo->addStandard('job', $jobStandard);
```

In that example,  \Shairyar\Job\Standard must extend [StandardAbstract](https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/StandardAbstract.php) to define all parsing rules for this particular feed. Keep in mind that feed-io doesn't introspect feeds to parse them, it recognizes them by their convention. This is done by the [canHandle method](https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/Standard/Rss.php) defined in Standard classes, that's why there're important.

I hope it helped !

Alex

**Comment by shairyar** [comment]
Many thanks, I will go through the links you sent, they look helpful.
